apiVersion: v1
kind: Service
metadata:
  name: seerr
  labels:
    app: seerr
spec:
  type: NodePort
  selector:
    app: seerr
  ports:
    - name: http
      port: 5055
      targetPort: http
      nodePort: 30555
      protocol: TCP
